language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - npm test
notifications:
  email:
    - h_portela@hotmail.com
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: hpportela-travis-heroku-test
